version: '2.1'
services:


  energy_platform_backend:
    image: energy-platform-backend
    ports:
      - "8080:8080"
    depends_on:
       energy_platform_db:
          condition: service_healthy

    container_name: backend_container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/energy-utility-platform-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  energy_platform_db:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 20s
      retries: 5
    ports:
      - "5432:5432"
    container_name: database
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=energy-utility-platform-db
      - POSTGRES_HOST_AUTH_METHOD=trust


  energy_platform_app:
    image:  energy-platform-frontend
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    container_name: frontend_container